#!/bin/bash
# Copyright © 2016 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

virtualenv=virtualenv

if [[ -d "$virtualenv" ]]
then
    echo "The virtual environment already exists."
    exit 1
fi

virtualenv-3 "$virtualenv"

PS1=
source "$virtualenv/bin/activate"

pip3 install django
