# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DilutionScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Eigensystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Ensemble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mu_l', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Perambulator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_seed', models.IntegerField()),
                ('mass_light', models.FloatField()),
                ('mass_strange', models.FloatField()),
                ('mass_charm', models.FloatField()),
                ('dilution_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lqcd_inventory.DilutionScheme')),
                ('ensemble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lqcd_inventory.Ensemble')),
            ],
        ),
        migrations.AddField(
            model_name='eigensystem',
            name='ensemble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lqcd_inventory.Ensemble'),
        ),
    ]
