# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lqcd_inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DilutionScheme',
            new_name='Dilution',
        ),
    ]
