# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lqcd_inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ensemble',
            old_name='mu_l',
            new_name='mass_light',
        ),
    ]
